#!/usr/bin/env bash
# run_all.sh
# Master script — runs the full pipeline from scratch on a fresh Ubuntu machine.
#
# BEFORE RUNNING:
#   Edit the CONFIG block below. This script auto-generates .env from these
#   values, so do NOT create .env manually — it will be overwritten.
#
#   Required:
#     DB_PASSWORD  — set a real password (default "postgres" is insecure)
#
#   Optional:
#     HF_TOKEN     — Hugging Face API token for higher download rate limits.
#                    Get a free read-only token at:
#                    https://huggingface.co/settings/tokens
#                    Leave empty to use unauthenticated access (slower on
#                    busy days but always works).
#
#     INGEST_LIMIT — number of AG News articles to embed (default: 5000).
#                    The full dataset has ~120,000 articles.
set -euo pipefail

# ── CONFIG ────────────────────────────────────────────────────────────────────
DB_NAME="semantic_search"
DB_USER="postgres"
DB_PASSWORD="postgres"       # change this!
INGEST_LIMIT=5000            # number of documents to ingest
BATCH_SIZE=64
HF_TOKEN=""                  # optional — paste your HF token here
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Produce the HF_TOKEN line for .env: active if set, commented out if empty.
if [ -n "$HF_TOKEN" ]; then
    HF_TOKEN_LINE="HF_TOKEN=$HF_TOKEN"
else
    HF_TOKEN_LINE="# HF_TOKEN=hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
fi

# Generate .env from the CONFIG block above.
# All Python scripts load this file via python-dotenv.
cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by run_all.sh — edit the CONFIG block in that file, not here.

# PostgreSQL connection
DB_HOST=localhost
DB_PORT=5432
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Embedding model
EMBEDDING_MODEL=all-MiniLM-L6-v2

# Search settings
TOP_K=10
BATCH_SIZE=$BATCH_SIZE

# Hugging Face API token (optional).
# Enables higher download rate limits for datasets and models from the Hub.
# Get a free read-only token at https://huggingface.co/settings/tokens
# To activate: set HF_TOKEN in the CONFIG block at the top of run_all.sh.
$HF_TOKEN_LINE

# Forces CPU inference and suppresses PyTorch's CUDA driver version warning.
# PyTorch emits this warning when the installed NVIDIA driver is too old
# (driver < 525 for CUDA 12). The model falls back to CPU automatically.
# Remove this line once the driver is updated (sudo apt install nvidia-driver-535).
CUDA_VISIBLE_DEVICES=
EOF
echo "[run_all] .env written."

echo "Semantic Search Engine - Full Pipeline"

# Make all scripts executable
chmod +x "$SCRIPT_DIR"/scripts/*.sh

echo "Step 1/6: Install dependencies"
bash "$SCRIPT_DIR/scripts/01_install_deps.sh"

echo ""
echo "Step 2/6: Configure PostgreSQL"
bash "$SCRIPT_DIR/scripts/02_setup_postgres.sh"

echo ""
echo "Step 3/6: Apply database schema"
bash "$SCRIPT_DIR/scripts/03_init_schema.sh"

echo ""
echo "Step 4/6: Ingest dataset (limit=$INGEST_LIMIT)"
LIMIT=$INGEST_LIMIT BATCH_SIZE=$BATCH_SIZE \
    bash "$SCRIPT_DIR/scripts/04_ingest.sh"

echo ""
echo "Step 5/6: Run evaluation"
bash "$SCRIPT_DIR/scripts/06_evaluate.sh"

echo ""
echo "Step 6/6: Pipeline complete."
echo "To search interactively: bash scripts/05_search.sh"
echo "Single query:            bash scripts/05_search.sh \"your query\""
